#!/bin/bash -e
mkdir -p output
docker run \
    --rm \
    -ti \
    --network=host \
    --device=/dev/kfd \
    --device=/dev/dri \
    --group-add=video \
    --ipc=host \
    --cap-add=SYS_PTRACE \
    --security-opt seccomp=unconfined \
    -v `pwd`/output:/output \
    rocm \
    "$@"
