#!/usr/bin/env -S bash -e
mkdir -p output
test -h models/model.ckpt || ln -s sd-v1-4.ckpt models/model.ckpt
docker run \
    --rm \
    -ti \
    --network=host \
    --device=/dev/kfd \
    --device=/dev/dri \
    --group-add=video \
    --ipc=host \
    --cap-add=SYS_PTRACE \
    --security-opt seccomp=unconfined \
    -v `pwd`/output:/output \
    -v `pwd`/models:/models \
    rocm \
    "$@"
